---
title: "MATH/COSC 3570 Introduction to Data Science (Spring 2026)"
tbl-colwidths: [5,8,20,10,10,8,8]
---

*This schedule will be updated as the semester progresses, with all changes documented here*.

::: column-screen-inset-right
| Week | Date | Topic | Materials | Lab Activity | AI Activity | Project |
|:---------:|-----------|-----------|:---------:|:---------:|:---------:|-----------|
| 1 | Tue, Jan 13 | Greetings; Overview of Data Science | [🖥️syllabus](slides/01-syllabus-slides.html) [🖥️overview](slides/02-datascience-slides.html) |  |  |  |
|  | Thu, Jan 15 | Posit Cloud | [🖥️posit](slides/03-posit-slides.html) | [📋 posit](/exercise/lab00-posit.html) [📋01](/exercise/lab01-rscript.html) |  |  |
| 2 | Tue, Jan 20 | Git and GitHub | [🖥️git](slides/04-git-slides.html) | [📋github](/exercise/lab00-git.html) |  |  |
|  | Thu, Jan 22 | Quarto: YAML and Markdown | [🖥️quarto](slides/05-quarto-slides.html) | [📋02](/exercise/lab02-quarto.html) [📋03](/exercise/lab03-markdown.html) |  | [✅ Team up!](team.html) |
| 3 | Tue, Jan 27 | Quarto: Code Chunk |  | [📋04](/exercise/lab04-chunk.html) |  |  |
|  | Thu, Jan 29 | R and Python Syntax | [🖥️syntax](/slides/06-syntax-slides.html) | [📋05](/exercise/lab05-rtype.html) [📋06](/exercise/lab06-py.html) |  | Team up Due! |
| 4 | Tue, Feb 3 | R Tidyverse | [🖥️package](/slides/07-package-slides.html) | [📋07](/exercise/lab07-plot.html) [📋08](/exercise/lab08-tibble.html) | [🤖 AI Project Guideline](/ai_act_guide.html) |  |
|  | Thu, Feb 5 | Python NumPy/Pandas |  | [📋09](/exercise/lab09-numpy.html) |  |  |
| 5 | Tue, Feb 10 | Data Importing | [🖥️import](/slides/08-import-slides.html) | [📋10](/exercise/lab10-import.html) |  |  |
|  | Thu, Feb 12 | Data Visualization-ggplot2 | [🖥️ggplot](/slides/09-ggplot2-slides.html) | [📋11](/exercise/lab11-ggplot2.html) [📋Extra credit](/exercise/lab-extra.html) |  |  |
| 6 | Tue, Feb 17 | Data Visualization-categorical and numerical data | [🖥️visualization](/slides/10-viz-slides.html) | [📋12](/exercise/lab12-facet.html) [📋13](/exercise/lab13-visualization.html) | [Activity 1](ai/ai_1.html) |  |
|  | Thu, Feb 19 | ~~Interactive Data Visualization~~ | [🖥️interactive-viz](/slides/11-interactive-viz-slides.html) | [📋14](/exercise/lab14-interactive.html) (optional) |  |  |
| 7 | Tue, Feb 24 | Data Wrangling - one data frame | [🖥️dplyr-1](/slides/12-dplyr-1-slides.html) | [📋15](/exercise/lab15-dplyr.html) |  |  |
|  | Thu, Feb 26 | Data Wrangling - two data frames | [🖥️dplyr-2](/slides/13-dplyr-2-slides.html) | [📋16](/exercise/lab16-join.html) | [elec_vote_y](/slides/data/results_us_election_2016.csv) |  |
| 8 | **Tue, Mar 3** | [**Mini Project 1 Presentation: Exploratory Data Storytelling**](/project/mini_project_1.html) |  |  |  |  |
|  | Thu, Mar 5 | Data Wrangling - tidyr | [🖥️ tidyr](/slides/14-tidyr-slides.html) | [📋17](/exercise/lab17-tidyr.html) | [Activity 2](ai/ai_2.html) |  |
| 9 | Tue, Mar 10 | ***NO CLASS: Spring break*** |  |  |  |  |
|  | Thu, Mar 12 | ***NO CLASS: Spring break*** |  |  |  |  |
| 10 | Tue, Mar 17 | Probabilistic and Statistical Simulation | [🖥️probstat](/slides/15-probstat-slides.html) | [📋18](/exercise/lab18-prob.html) [📋19](/exercise/lab19-ci.html) |  |  |
|  | Thu, Mar 19 | Linear Regression | 🖥️linear-regression |  | [Activity 3](ai/ai_3.html) |  |
| 11 | Tue, Mar 24 | Multiple Linear Regression |  | 📋20 |  |  |
|  | **Thu, Mar 26** | **Mini Project 2 Presentation: Data Wrangling and Pipelines** |  |  |  |  |
| 12 | Tue, Mar 31 | Logistic Regression | 🖥️logistic-regression |  | Activity 4 |  |
|  | Thu, Apr 2 | ***NO CLASS: Easter break*** |  |  |  |  |
| 13 | Tue, Apr 7 | Logistic Regression |  | 📋21 |  |  |
|  | Thu, Apr 9 | K-Nearest Neighbors | 🖥️ K-Nearest Neighbors |  | Activity 5 |  |
| 14 | Tue, Apr 14 | Decision Trees | 🖥️ Decision Trees | 📋22 |  |  |
|  | **Thu, Apr 16** | **Mini Project 3 Presentation: Supervised Learning** |  |  |  |  |
| 15 | Tue, Apr 21 | Principal Component Analysis | 🖥️Principal Component Analysis |  |  |  |
|  | Thu, Apr 23 | Principal Component Analysis |  | 📋23 | Activity 6 | 📂 Final Project Proposal Due |
| 16 | Tue, Apr 28 | K-Means Clustering | 🖥️K-means Clustering |  |  |  |
|  | Thu, Apr 30 | K-Means Clustering |  | 📋24 |  |  |
| 17 | **Mon, May 4** | **Final Project Presentation (10:30 AM - 12:30 PM)** |  |  |  | 📂 Final Project Materials Due |
:::

Dr. Yu reserves the right to make changes to the schedule.

```{r echo = FALSE}
knitr::knit_exit()
```

|   |   |   | Prepare | Slides | AE | Labs | HW | Present | Project |
|--------|--------|--------|:------:|:------:|:------:|:------:|:------:|:------:|:------:|
| Week | Date | Topic | 📖 | 🖥️ | 📋 | [💻](https://sakai.duke.edu/samigo-app/servlet/Login?id=6fa7ebf3-01af-42a6-91ba-3e813d3901221641094171786) | ✍️ | ✅ | 📂 |
