---
title: "Lab 09: NumPy and pandas"
editor: source
reference-location: margin
execute:
  freeze: true
  echo: false
---

```{r}
#| message: false
knitr::opts_chunk$set(
    fig.asp = 0.618,
    fig.align = "center",
    out.width = "100%",
    fig.retina = 10,
    fig.path = "../slides/images/07-package/",
    message = FALSE,
    global.par = TRUE
)
library(fontawesome)
library(tidyverse)
```

::: callout-note

:::

In **lab.qmd** `## Lab 9` section, create a Python pandas.DataFrame equivalent to the R tibble


```{r}
#| echo: true
library(tibble)
tibble(x = 1:5, y = 5:1, z = LETTERS[1:5])
```


```{python}
#| echo: true
#| eval: false
import numpy as np
import pandas as pd
dic = {'__': np.arange(__, __), 
       '__': np.arange(__, __, __),
       '__': [, , , , ]}
pd._____________(dic)
```


```{python}
#| echo: false
#| eval: false
import numpy as np
import pandas as pd
import string
list(string.ascii_uppercase)
dic = {'__': ____________, 
       '__': reversed(____________),
       '__': list(string.ascii_uppercase)[______]}
pd._____________(dic)
```