---
title: "Lab 05: R Data Type Summary"
editor: source
reference-location: margin
execute:
  freeze: true
  echo: false
---

```{r}
knitr::opts_chunk$set(
    fig.asp = 0.618,
    fig.align = "center",
    out.width = "100%",
    fig.retina = 10,
    fig.path = "../slides/images/06-syntax/",
    message = FALSE,
    global.par = TRUE
)
library(fontawesome)
```

::: callout-note

:::

In **lab.qmd** Lab 5,

- Create R objects vector `v1`, factor `f2`, list `l3`, matrix `m4` and data frame `d5`.

- Check `typeof()` and `class()` of those objects, and create a list having the output below.


```{r}
#| class-output: my_classfull
#| echo: true
#| eval: false

v1 <- c(__________)
f2 <- f_____(__________)
l3 <- l_____(__________)
m4 <- m_____(__________)
d5 <- d_____.f_____(__________)
v <- c(type = typeof(v1), class = class(v1))
f <- c(type = __________, class = _________)
l <- c(type = __________, class = _________)
m <- c(type = __________, class = _________)
d <- c(type = __________, class = _________)
____(vec    =   v,
     ______ = ___,
     ______ = ___,
     ______ = ___,
     ______ = ___)
```

```{r}
v1 <- c(3, 8, 4, 5)
fac <- factor(c("med", "high", "low"))
x_lst <- list(idx = 1:3, 
              "a", 
              c(TRUE, FALSE))
mat <- matrix(data = 1:6, nrow = 3, ncol = 2)
df <- data.frame(age = c(19, 21, 40), 
                  gen = c("m","f", "m"))
v <- c(type = typeof(v1), class = class(v1))
f <- c(type = typeof(fac), class = class(fac))
l <- c(type = typeof(x_lst), class = class(x_lst))
m <- c(type = typeof(mat), class = class(mat))
d <- c(type = typeof(df), class = class(df))
list(vec = v,
     fac = f,
     lst = l,
     mat = m,
     df = d)
```
