---
title: "Lab 13: Visualization"
editor: source
reference-location: margin
execute:
  freeze: true
  echo: true
---

```{r}
#| echo: false
#| message: false
knitr::opts_chunk$set(
    fig.asp = 0.618,
    fig.align = "center",
    out.width = "100%",
    fig.retina = 10,
    fig.path = "../slides/images/10-viz/",
    message = FALSE,
    global.par = TRUE
)
library(fontawesome)
library(tidyverse)
```

::: callout-note

:::

In **lab.qmd** `## Lab 13` section,

- Import the data **penguins.csv**.

- Generate the following

```{r}
#| echo: false
library(tidyverse)
penguins <- read_csv("../slides/data/penguins.csv")
ggplot(data = penguins, aes(x = species, fill = species)) +
    geom_bar() +
    labs(x = "Species of Penguins", 
         title = "Species Counts in Penguins Data")
```


```{r}
#| echo: false
ggplot(penguins, aes(x = bill_length_mm, 
                     fill = species)) +
    geom_histogram() +
    labs(x = "Bill Length (mm)",
         y = "Frequency",
         title = "Penguins Bill Length by Species") +
    facet_wrap(~ species, nrow = 1) + 
    theme(legend.position = "none")

```



```{r}
#| echo: true
#| eval: false
# library(tidyverse)
penguins <- read_csv(__________________)
________ |> ggplot(_______________________) +  ## mapping layer  
    ___________________ +  ## geometry layer
    _____________________________  ## label layer
```

<br>
<br>
<br>


```{r}
#| echo: true
#| eval: false
________ |> ggplot(______________________________) +  ## mapping layer  
    _______________ +  ## geometry layer
    _______________ +  ## label layer
    ______________________________  +   ## facet layer
    ______________________________      ## theme layer (set legend.position = "none")

```

